apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: yolobackendcontainer
          image: mngaruiya/backend_k8s:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: backend
                key: PORT
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: MONGODB_URI

          
          