apiVersion: v1
kind: Secret
metadata:
   name: backend-secret
data:
   MONGODB_URI: "bW9uZ29kYjovL2RvY2tlcjp5YXIxMjNAYWMtMW1ncHhscS1zaGFyZC0wMC0wMC52Y3VuYXphLm1vbmdvZGIubmV0OjI3MDE3LGFjLTFtZ3B4bHEtc2hhcmQtMDAtMDEudmN1bmF6YS5tb25nb2RiLm5ldDoyNzAxNyxhYy0xbWdweGxxLXNoYXJkLTAwLTAyLnZjdW5hemEubW9uZ29kYi5uZXQ6MjcwMTcvP3NzbD10cnVlJnJlcGxpY2FTZXQ9YXRsYXMtdXcwbzd1LXNoYXJkLTAmYXV0aFNvdXJjZT1hZG1pbiZyZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk="