apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
spec:
  replicas: 
  selector:
    matchLabels:
      app: backend
  serviceName: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mongo:5.0.16
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: backend
                key: PORT
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: MONGODB_URI

          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts: 
          
            -   name: mongodb-persistent-storage
                mountPath: /data/db
      volumes: 
          
         -  name: mongodb-persistent-storage
            persistentVolumeClaim: 
              claimName: backend-pvc